### PR TITLE
feat: adds swahili translation

### PR DESCRIPTION
**Pull request by prosazhin**
This pull request adds the swahili version of the pages.

Pages on which the translation should be:

- [x] header
- [x] footer
- [x] SEO
- [x] [home](https://deploy-preview-533--ebpfio.netlify.app/sw/)
- [x] [what-is-ebpf](https://deploy-preview-533--ebpfio.netlify.app/sw/what-is-ebpf/)
- [x] [get-started](https://deploy-preview-533--ebpfio.netlify.app/sw/get-started/)
- [x] [case-studies](https://deploy-preview-533--ebpfio.netlify.app/sw/case-studies/)
- [x] [labs](https://deploy-preview-533--ebpfio.netlify.app/sw/labs/)
- [x] [events](https://deploy-preview-533--ebpfio.netlify.app/sw/events/)
- [x] [applications](https://deploy-preview-533--ebpfio.netlify.app/sw/applications/)
- [x] [infrastructure](https://deploy-preview-533--ebpfio.netlify.app/sw/infrastructure/)
- [x] [contribute](https://deploy-preview-533--ebpfio.netlify.app/sw/contribute/)

### CODE REVIEW

**Comment by xmulligan** [comment]
@hacktivist123 can you get the contribute page translated?

**Comment by prosazhin** [comment]
@xmulligan Hello! The translation is ready, feel free to review it.

**Review by americano98 — APPROVED** [review]

**Comment by hacktivist123** [comment]
Screenshot 2023-11-30 at 14 06 00

Can you replace this text with, this is a shorter form

> Panga kernel kwa uthabiti kwa ajili ya utendakazi bora wa mtandao, uangalizi, ufuatiliaji na usalama

other than this change, it generally LGTM! @prosazhin @xmulligan

**Comment by prosazhin** [comment]
@xmulligan @hacktivist123 Done! Please have a look.

**Comment by hacktivist123** [comment]
> @xmulligan @hacktivist123 Done! Please have a look.

LGTM!

**Review by hacktivist123 — APPROVED** [review]

**Pull request merged**
