### PR TITLE
docs: add PcapPlusPlus to the list of emerging applications

### PR DESCRIPTION
**Pull request by seladb**
Hi there 👋 , it's [PcapPlusPlus](https://github.com/seladb/PcapPlusPlus) maintainer! We recently added an option to create and work with AF_XDP sockets: https://pcapplusplus.github.io/docs/next/features#af_xdp-support-beta

Please let me know if you'll consider adding PcapPlusPlus to the list of emerging applications.

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for the addition @seladb Can you help me a bit understand how the project fits the criteria?

"The project must be using eBPF as its underlying core technology (in other words, a project would lose its purpose if the eBPF parts are removed) or help accelerate the adoption of eBPF in production."

**Comment by seladb** [comment]
> Thanks for the addition @seladb Can you help me a bit understand how the project fits the criteria?
> 
> "The project must be using eBPF as its underlying core technology (in other words, a project would lose its purpose if the eBPF parts are removed) or help accelerate the adoption of eBPF in production."

Well, of course PcapPlusPlus won't lose its purpose if the eBPF parts are removed, mostly because eBPF / XDP support is very new, but we will consider adding more eBPF-related features in the future, depending on adoption and demand.
However, the way I see it, this page on the eBPF web-site describes the ecosystem around eBPF and I think PcapPlusPlus can be part of it. [DPDK has a similar page](https://www.dpdk.org/ecosystem/) and so as [libpcap](https://www.tcpdump.org/related.html) and PcapPlusPlus is part of those web-sites too. I hope you agree with me on it, or maybe there's a different place on the web-site where this project can be added?

**Comment by xmulligan** [comment]
How would you feel about adding it to https://ebpf.io/infrastructure/#ebpf-auxiliary-libraries?

**Comment by seladb** [comment]
> How would you feel about adding it to https://ebpf.io/infrastructure/#ebpf-auxiliary-libraries?

Sure @xmulligan , done in https://github.com/ebpf-io/ebpf.io-website/pull/546/commits/ff4f9893f443cabaa35b6c0b50df2ef2ad96c221

**Comment by xmulligan** [comment]
Thanks!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
