### PR TITLE
feat: update link

### PR DESCRIPTION
**Pull request by nikvoblikov**
**This PR:**
Updates the link to the store.
Adds eBPF Summit to Events.

**Steps to test**

- Open the [Swag page](https://deploy-preview-427--ebpfio.netlify.app/swag/)
- Open the [Events page](https://deploy-preview-427--ebpfio.netlify.app/events/)
- Confirm that everything looks and works as expected

### CODE REVIEW

**Review by vannyle — APPROVED** [review]

**Comment by xmulligan** [comment]
The swag store, seems to be linked to the 2022 summit. So if I click to the swag page, then go home it goes to 2022 not 2023. The swag is also all of 2022 rather than 2023

**Comment by xmulligan** [comment]
ahh ok, great thanks. Let me know when this is ready to merge

**Comment by nikvoblikov** [comment]
> ahh ok, great thanks. Let me know when this is ready to merge

Now it is ready :)

**Comment by xmulligan** [comment]
Seems like it doesn't show up in the eBPF Summit events filter. Can you make sure it is added there too?

**Comment by nikvoblikov** [comment]
> Seems like it doesn't show up in the eBPF Summit events filter. Can you make sure it is added there too?

This is due to the filtering system - if an event is featured, then it does not fall into the main list and is not filtered.

Now we are removing the Hero section with a featured events and changing the filtering system. I propose to merge this PR and wait for the next one, which we plan to finish today.

**Pull request merged**
