### PR TITLE
feat: 404 page

### PR DESCRIPTION
**Pull request by nerucheva**
This PR adds new markup for 404 page
[Preview](https://deploy-preview-393--ebpfio.netlify.app/404)

### CODE REVIEW

**Review by xmulligan — APPROVED** [review]

**Comment by qmonnet** [comment]
This does not work?? It only displays for https://ebpf.io/404, it should be for any page we can't find, such as https://ebpf.io/foobar etc.?

**Comment by xmulligan** [comment]
@nerucheva can you fix this?

**Comment by vannyle** [comment]
Hi, I've fixed the issue, it doesn't work, as there was an old redirect to summit pages. The redirect has been removed, and the 404 page should work properly after merging this [PR](https://github.com/ebpf-io/ebpf.io-website/pull/395)

**Comment by nerucheva** [comment]
@vannyle Thank you for your help!

**Pull request merged**
