### PR TITLE
feat: changes get-started page

### PR DESCRIPTION
**Pull request by prosazhin**
**Describe what changes this pull request brings**
This pull request changes on the get-started page.

**Useful links:**
[Link to page design in Figma](https://www.figma.com/file/DKNPEcutVbDZb1ylyP7wHs/EBPF-Website-Design?type=design&node-id=3409%3A42528&mode=dev)

**Steps to test**
1. Open the [page](https://deploy-preview-467--ebpfio.netlify.app/get-started/)
1. Confirm that everything looks and works as expected

**TODO: before deployment**
- [x] Hide contributor list:

### CODE REVIEW

**Review by andrewgolovanov — APPROVED** [review]

**Comment by xmulligan** [comment]
For the link under the community header, can you link to the documentation section of the page?

Screenshot 2023-09-11 at 13 17 21

**Comment by prosazhin** [comment]
@xmulligan Ready to check

**Comment by xmulligan** [comment]
seems the link still just goes to the top of the page

**Comment by prosazhin** [comment]
@xmulligan Ready to check

**Comment by xmulligan** [comment]
@prosazhin thanks looks good. If you can resolve the conflicts from merging #476 then we can merge it

**Comment by prosazhin** [comment]
@xmulligan Correcting errors after adding a translation will require additional time

**Comment by prosazhin** [comment]
@xmulligan Corrected the conflicts. But in order for changes to be sent, it is necessary to add a translation for new blocks. For the new block of contributors, you don’t have to add a translation for now, because it’s still hidden.

- [ ] Title for the event block
- [ ] Link for the event block
- [ ] Title for a block of posts
- [ ] Link for a block of posts

**Comment by xmulligan** [comment]
final translations https://docs.google.com/document/d/1CyOBQcn-7IKj1LMQgxYPL7Kt6asZ_2yiPzdqgbaw0w0/edit

**Comment by prosazhin** [comment]
@xmulligan Requested access to a file

**Comment by xmulligan** [comment]
I've added you now

**Comment by prosazhin** [comment]
@xmulligan Ready to check

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
