### PR TITLE
feat: Adds simplified chinese

### PR DESCRIPTION
**Pull request by C7ovis**
Hi team,

This pull request adds the Chinese version[Simlified] of the pages. Me and @jaffcheng have them translated, please review, thank you.

Pages on which the translation should be:

- [x] header
- [x] footer
- [x] SEO
- [x] [home](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/)
- [x] [what-is-ebpf](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/what-is-ebpf/)
- [x] [get-started](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/get-started/)
- [x] [case-studies](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/case-studies/)
- [x] [labs](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/labs/)
- [x] [events](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/events/)
- [x] [applications](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/applications/)
- [x] [infrastructure](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/infrastructure/)
- [x] [contribute](https://deploy-preview-532--ebpfio.netlify.app/zh-cn/contribute/)

### CODE REVIEW

**Comment by C7ovis** [comment]
HI,

I cant figure out why it runs into this markdown render problem ? Could someone please help with this ?
https://deploy-preview-532--ebpfio.netlify.app/zh-cn/what-is-ebpf/#%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7%E9%93%BE

image

**Comment by prosazhin** [comment]
@C7ovis @xmulligan Hello. Not all text in the footer has been translated.
Снимок экрана 2023-11-28 в 13 41 17

**Comment by prosazhin** [comment]
@C7ovis @xmulligan On the "/zh-cn/case-studies/" page, there is no translation for the subtitle.

Снимок экрана 2023-11-28 в 14 24 58

**Comment by C7ovis** [comment]
Hi @prosazhin ,

Thank you for help resolve the markdown render problem,

#1 was thinking maybe better to keep the original eng, but then I refered to https://kubernetes.io/zh-cn/docs/home/ yes you are right
#2 have this missing part translated

Just have both of them translated :)

**Comment by C7ovis** [comment]
Looks like I now can watch the video, and also have the film / documentary part translated on home page

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
