### PR TITLE
Add: sticky header

### PR DESCRIPTION
**Pull request by frozenprocess**
A simple sticky header that doesn't leave a big gap at the top :)

https://github.com/ebpf-io/ebpf.io-website/issues/268 <- fixes this

### CODE REVIEW

**Comment by frozenprocess** [comment]
Not sure why there are multiple headers 😕 btw.

**Comment by vannyle** [comment]
@frozenprocess thank you for contributing to eBPF. It looks great, but is there any reason why the sticky header can't be done just with CSS?

**Comment by frozenprocess** [comment]
Yes, I believe the presence of elements above the header greatly influenced my decision.

`introDisclaimer` renders above the header, which will make CSS only version of sticky implmentation a bit silly, leaving 95px gap at the top.
image

There might be a possibility to do some sort of hacky `scroll-behavior` for a CSS only, but since there are two headers 😕 (`header desktop`,`header mobile`) and both are implemented with Javascript, it is going to be tad bit complicated to pull it off.

**Comment by vannyle** [comment]
> Yes, I believe the presence of elements above the header greatly influenced my decision.
> 
> `introDisclaimer` renders above the header, which will make CSS only version of sticky implmentation a bit silly, leaving 95px gap at the top. image
> 
> There might be a possibility to do some sort of hacky `scroll-behavior` for a CSS only, but since there are two headers 😕 (`header desktop`,`header mobile`) and both are implemented with Javascript, it is going to be tad bit complicated to pull it off.

I'm not sure if `introDisclaimer` is an issue. I've tried to use CSS to implement the sticky header. It seems work to me without a gap. 
image
image

**Comment by frozenprocess** [comment]
Didn't `position: sticky` had some issues with opera or edge?
Apologies, I'm not actively following the browser changes anymore.

**Comment by vannyle** [comment]
> Didn't `position: sticky` had some issues with opera or edge? Apologies, I'm not actively following the browser changes anymore.

I did check on opera and edge via browserstack, no bug was spotted. Also, recording to [caniuse](https://caniuse.com/css-sticky) `position:sticky` is supported in latest versions of browsers.

**Comment by frozenprocess** [comment]
Great then I'll change my PR.
Thanks for the review!

**Review by vannyle — APPROVED** [review]
LGTM! Thank you 💯

**Comment by frozenprocess** [comment]
You know things have changed a lot when even google defines your method as old :smile: https://developer.chrome.com/blog/stick-your-landings-position-sticky-lands-in-webkit/#old-approach-scroll-events

**Comment by xmulligan** [comment]
@frozenprocess Thank you for submitting the issue and the fix, we appreciate it :)

**Pull request merged**
