### PR TITLE
Add Odigos to emerging applications

### PR DESCRIPTION
**Pull request by edeNFed**
This PR adds Odigos to the list of emerging applications.

eBPF code can be found here:
https://github.com/keyval-dev/opentelemetry-go-instrumentation

### CODE REVIEW

**Comment by edeNFed** [comment]
@xmulligan I'll be happy to get your review for this 🙏🏻

**Comment by xmulligan** [comment]
Sorry was on summer holiday, just coming back to this now

**Comment by xmulligan** [comment]
@edeNFed it looks like you forgot to add the logo? Can you add the file too?

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
Thanks for the addition and your patience!

**Pull request merged**
