### PR TITLE
Add BPF as synonym of eBPF

### PR DESCRIPTION
**Pull request by dthaler**
Per BSC discussion 12/14/22.

BSC members please check if this matches what the consensus was in the meeting.  I took an action to do this PR but you all should tell me if the wording is incorrect.

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

### CODE REVIEW

**Comment by dthaler** [comment]
@ebpffoundation/ebpf-bsc please review and suggest edits if needed.

**Comment by dthaler** [comment]
@anakryiko @brendangregg @borkmann @joestringer @lmb @sinkap please review and suggest edits if needed.

**Review by borkmann — APPROVED** [review]

**Review by anakryiko — APPROVED** [review]

**Review by lmb — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by xmulligan** [comment]
Would you mind if we moved this into a separate question like "What does eBPF and BPF stand for?". I think the first sentence is getting a little long just defining the term before getting into what it actually does

**Comment by xmulligan** [comment]
I've made my suggestions in #320. Let me know what you think ☃️

**Comment by xmulligan** [comment]
Closing since #320 is merged.

**Pull request closed without merging**
