### PR TITLE
feat: adds french language

### PR DESCRIPTION
**Pull request by prosazhin**
**Describe what changes this pull request brings**
This pull request adds French language.

**Useful links:**
[Link to the language selection design in the footer in Figma](https://www.figma.com/file/DKNPEcutVbDZb1ylyP7wHs/EBPF-Website-Design?type=design&node-id=3324%3A45867&mode=design&t=CYnIqgPO1l7g19LB-1)

**Steps to test:**
1. Open the [index page](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/), [what-is-ebpf page](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/), [get-started page](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/get-started/), [case-studies page](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/case-studies/), [contribute page](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/contribute/)
1. Confirm that everything looks and works as expected

**TODO:**
- [x]  Language switch select in header
- [x]  Translation of header navigation
- [x]  Translation of footer navigation
- [ ]  ~~Translation all text for case-studies page~~
- [x]  There is no translation for the title and subtitle on the "case-studies" page
- [x]  On the main page in the first block there is no translation for the "Project Landscape" and "What is eBPF" buttons
- [ ]  ~~Translation all text for what-is-ebpf page (On the "what is ebpf" page in the last block "Further Reading" only the headings are translated)~~
- [x]  Translation SEO meta tags

### CODE REVIEW

**Comment by doniacld** [comment]
In the section Lectures complémentaires the different sub-sections are in English:
[Lectures complémentaires](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#lectures-compl%C3%A9mentaires)
[Documentation](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#documentation)
[Tutorials](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#tutorials) --> Tutoriels
[Talks](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#talks)
[Books](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#books) --> Livres
[Articles & Blogs](https://deploy-preview-476--ebpfio.netlify.app/fr-fr/what-is-ebpf/#articles--blogs)

**Comment by doniacld** [comment]
Remove the additional coma: (updated in the google doc as a suggestion)
> À moins qu’une option dédiée ne soit activée,**,**

--> À moins qu’une option dédiée ne soit activée,

**Comment by xmulligan** [comment]
@prosazhin where is the actual content living?

Also would it be possible to have the language selector at the top of the page like we had before with different flags?

**Comment by doniacld** [comment]
There is a sentence in English that has not been translated, my bad sorry. 

> Programs may not use any uninitialized variables or access memory out of bounds.

Translation:
Les programmes ne peuvent pas utiliser des variables non initialisées ou accéder à de la mémoire en dehors des limites.

Added a suggestion in the gdoc.

**Comment by doniacld** [comment]
> BCC cible principalement les cas **d’uqui** impliquent

--> BCC cible principalement les cas **qui** impliquent

Suggestion added to gdoc.

**Comment by prosazhin** [comment]
> @prosazhin where is the actual content living?
> 
> Also would it be possible to have the language selector at the top of the page like we had before with different flags?

@xmulligan  I've conveyed to the designer that the language switch select in the header needs to be created.

**Comment by prosazhin** [comment]
> @prosazhin where is the actual content living?
> 
> Also would it be possible to have the language selector at the top of the page like we had before with different flags?

@xmulligan All content for translated pages into English and French is located in the data folder

**Comment by prosazhin** [comment]
@doniacld Made changes to the French text

**Comment by xmulligan** [comment]
For the language selector can you also make it the flag rather than a generic globe?

**Comment by xmulligan** [comment]
Then is this ready to ship?

**Comment by prosazhin** [comment]
> For the language selector can you also make it the flag rather than a generic globe?

I passed this on to our designer, he will prepare the flag icons. As soon as this is ready, I will change them in the code.

**Comment by prosazhin** [comment]
@xmulligan Added icons of country flags to the language selector in the site header

**Comment by xmulligan** [comment]
@doniacld can you translate the header and footer?

@prosazhin where can we find the SEO text that needs to be translated? And what text is missing on the what is ebpf page?

We are going to leave the case studies page as is for now because we will be updating it

**Comment by prosazhin** [comment]
@xmulligan On the "what is ebpf" page in the last block "Further Reading" only the headings are translated

**Comment by prosazhin** [comment]
@xmulligan On the main page in the first block there is no translation for the "Project Landscape" and "What is eBPF" buttons

**Comment by prosazhin** [comment]
@xmulligan There is no translation for the title and subtitle on the "case-studies" page

**Comment by prosazhin** [comment]
@xmulligan Data for SEO meta tags is located along the path "src/data/shared/seo-data.js"

**Review by andrewgolovanov — APPROVED** [review]

**Comment by xmulligan** [comment]
@doniacld can you also translate "Project Landscape" and "What is eBPF" buttons, title and subtitle on the "case-studies" page, and the SEO metadata?

**Comment by xmulligan** [comment]
@prosazhin final translations are here https://docs.google.com/document/d/1KHo92adRqHkWlvOmIBrw4BA5fKSN45mUtDSMhwAhNn8/edit

**Comment by prosazhin** [comment]
@xmulligan Ready to check

**Comment by xmulligan** [comment]
@prosazhin thanks. It looks like there are still some conflicts to resolve. Also on the homepage when you click on the landscape button it 404s. I think it is because you didn't set up the french translation for the landscape pages

**Comment by prosazhin** [comment]
@xmulligan Ready to check

**Comment by xmulligan** [comment]
Sorry @prosazhin one last thing. When you click on the landscape, it switches to the english version of the website. Can you keep it on the French version? Otherwise people might get confused

**Pull request merged**
