### PR TITLE
projects: Add pwru to emerging projects

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Comment by qmonnet** [comment]
pwru does meet the requirements to be listed as an emerging project :+1: 

> The ordering of emerging applications is based on the number of Github stars (high to low)

Can you insert pwru at the right location please? It looks like it should go between Bumblebee and ply.

Sadly I don't have the permissions to approve the preview build.

**Comment by brb** [comment]
> Can you insert pwru at the right location please? It looks like it should go between Bumblebee and ply.

@qmonnet Good spot, thanks.

**Comment by k8isdead** [comment]
@brb hi! your preview build has failed because of the wrong pwru logo location, could you please move it to the assets/project-logos folder?

**Comment by brb** [comment]
@k8isdead Hi, done, thanks!

**Review by borkmann — APPROVED** [review]

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
