### PR TITLE
add SentinelOne eBPF case study

### PR DESCRIPTION
**Pull request by s1-tkaspar**
New blog addition for your review.  Thanks in advance!

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for the addition, @s1-tkaspar . Looks like the preview isn't working, can you check why?

**Comment by s1-tkaspar** [comment]
> Thanks for the addition, @s1-tkaspar . Looks like the preview isn't working, can you check why?

Yes, I am investigating.  Thank you.

**Comment by s1-tkaspar** [comment]
> Thanks for the addition, @s1-tkaspar . Looks like the preview isn't working, can you check why?

Hi @xmulligan 

I successfully built and viewed the site locally.  I don't see anything related to the commit in the netlify error logs.  

Can you re-trigger the Preview deploy on your side, or do I need to add an empty commit?

**Comment by xmulligan** [comment]
Looks like it works now, can you move it to the end of the page though?

**Comment by s1-tkaspar** [comment]
> Looks like it works now, can you move it to the end of the page though?

Yes, it is now at the end.

**Comment by xmulligan** [comment]
Perfect, thanks!

**Pull request merged**
