### PR TITLE
docs: add dae to emerging applications

### PR DESCRIPTION
**Pull request by yqlbu**
## Summary

Add [dae](https://github.com/daeuniverse/dae) to eBPF projects page. In terms of requirements for inclusion in the projects page:

- [x] The project must be open source: dae is open-sourced under the AGPL-3.0 License
- [x] The project must be using eBPF as its underlying core technology
- [x] The project must be open to collaboration: including external contributors, we now have a total of 13 contributors
- [x] The project must be actively maintained

cc @xmulligan

### CODE REVIEW

**Comment by yqlbu** [comment]
cc @kunish @mzz2017.

**Comment by xmulligan** [comment]
Thanks for the addition! Would you mind putting it in order by Github stars and resolving the conflicts?

**Comment by yqlbu** [comment]
> Thanks for the addition! Would you mind putting it in order by Github stars and resolving the conflicts?

Absolutely. I will take a closer look.

**Comment by yqlbu** [comment]
> Thanks for the addition! Would you mind putting it in order by Github stars and resolving the conflicts?

From what I can see, we have '800+` stars which is lower than the ones (1.2k) that deepflow has. I assume we are supposed to put in the order behind deepflow? Could you confirm that?

**Comment by yqlbu** [comment]
All resolved, feel free to review it again. Cheers!

**Comment by xmulligan** [comment]
Thanks for the updates and adding it to the landscape!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
